import { ReactNode, FC } from 'react'
import Head from 'next/head'

import Header from 'components/header'
import Footer from 'components/footer'
import styles from 'styles/Layout.module.css'

interface Props {
  children: ReactNode
}

const Layout: FC<Props> = (props: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FutaViewer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main className={styles.main}>{props.children}</main>
      <Footer />
    </div>
  )
}

export default Layout
